// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.2
// source: sst.proto

package sst

import (
	db "github.com/MartinSimango/simple-db/internal/db"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position     uint32        `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	UnsharedKey  []byte        `protobuf:"bytes,2,opt,name=unshared_key,json=unsharedKey,proto3" json:"unshared_key,omitempty"`
	SharedKeyLen uint32        `protobuf:"varint,3,opt,name=shared_key_len,json=sharedKeyLen,proto3" json:"shared_key_len,omitempty"`
	Value        []byte        `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	RecordType   db.RecordType `protobuf:"varint,5,opt,name=record_type,json=recordType,proto3,enum=db.RecordType" json:"record_type,omitempty"`
}

func (x *BlockEntry) Reset() {
	*x = BlockEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sst_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockEntry) ProtoMessage() {}

func (x *BlockEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sst_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockEntry.ProtoReflect.Descriptor instead.
func (*BlockEntry) Descriptor() ([]byte, []int) {
	return file_sst_proto_rawDescGZIP(), []int{0}
}

func (x *BlockEntry) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *BlockEntry) GetUnsharedKey() []byte {
	if x != nil {
		return x.UnsharedKey
	}
	return nil
}

func (x *BlockEntry) GetSharedKeyLen() uint32 {
	if x != nil {
		return x.SharedKeyLen
	}
	return 0
}

func (x *BlockEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *BlockEntry) GetRecordType() db.RecordType {
	if x != nil {
		return x.RecordType
	}
	return db.RecordType_RECORD_TYPE_UNSPECIFIED
}

type BlockHandle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset uint32 `protobuf:"fixed32,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Size   uint32 `protobuf:"fixed32,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *BlockHandle) Reset() {
	*x = BlockHandle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sst_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHandle) ProtoMessage() {}

func (x *BlockHandle) ProtoReflect() protoreflect.Message {
	mi := &file_sst_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHandle.ProtoReflect.Descriptor instead.
func (*BlockHandle) Descriptor() ([]byte, []int) {
	return file_sst_proto_rawDescGZIP(), []int{1}
}

func (x *BlockHandle) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *BlockHandle) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type IndexEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position     uint32       `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	UnsharedKey  []byte       `protobuf:"bytes,2,opt,name=unshared_key,json=unsharedKey,proto3" json:"unshared_key,omitempty"`
	SharedKeyLen uint32       `protobuf:"varint,3,opt,name=shared_key_len,json=sharedKeyLen,proto3" json:"shared_key_len,omitempty"`
	BlockHandle  *BlockHandle `protobuf:"bytes,4,opt,name=block_handle,json=blockHandle,proto3" json:"block_handle,omitempty"`
}

func (x *IndexEntry) Reset() {
	*x = IndexEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sst_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexEntry) ProtoMessage() {}

func (x *IndexEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sst_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexEntry.ProtoReflect.Descriptor instead.
func (*IndexEntry) Descriptor() ([]byte, []int) {
	return file_sst_proto_rawDescGZIP(), []int{2}
}

func (x *IndexEntry) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *IndexEntry) GetUnsharedKey() []byte {
	if x != nil {
		return x.UnsharedKey
	}
	return nil
}

func (x *IndexEntry) GetSharedKeyLen() uint32 {
	if x != nil {
		return x.SharedKeyLen
	}
	return 0
}

func (x *IndexEntry) GetBlockHandle() *BlockHandle {
	if x != nil {
		return x.BlockHandle
	}
	return nil
}

type DataBlockEntries struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*BlockEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *DataBlockEntries) Reset() {
	*x = DataBlockEntries{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sst_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataBlockEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBlockEntries) ProtoMessage() {}

func (x *DataBlockEntries) ProtoReflect() protoreflect.Message {
	mi := &file_sst_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBlockEntries.ProtoReflect.Descriptor instead.
func (*DataBlockEntries) Descriptor() ([]byte, []int) {
	return file_sst_proto_rawDescGZIP(), []int{3}
}

func (x *DataBlockEntries) GetEntries() []*BlockEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DataBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataBlockEntries *DataBlockEntries `protobuf:"bytes,1,opt,name=data_block_entries,json=dataBlockEntries,proto3" json:"data_block_entries,omitempty"`
	RestartPoints    []uint32          `protobuf:"varint,2,rep,packed,name=restart_points,json=restartPoints,proto3" json:"restart_points,omitempty"`
}

func (x *DataBlock) Reset() {
	*x = DataBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sst_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBlock) ProtoMessage() {}

func (x *DataBlock) ProtoReflect() protoreflect.Message {
	mi := &file_sst_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBlock.ProtoReflect.Descriptor instead.
func (*DataBlock) Descriptor() ([]byte, []int) {
	return file_sst_proto_rawDescGZIP(), []int{4}
}

func (x *DataBlock) GetDataBlockEntries() *DataBlockEntries {
	if x != nil {
		return x.DataBlockEntries
	}
	return nil
}

func (x *DataBlock) GetRestartPoints() []uint32 {
	if x != nil {
		return x.RestartPoints
	}
	return nil
}

type IndexEntries struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*IndexEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *IndexEntries) Reset() {
	*x = IndexEntries{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sst_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexEntries) ProtoMessage() {}

func (x *IndexEntries) ProtoReflect() protoreflect.Message {
	mi := &file_sst_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexEntries.ProtoReflect.Descriptor instead.
func (*IndexEntries) Descriptor() ([]byte, []int) {
	return file_sst_proto_rawDescGZIP(), []int{5}
}

func (x *IndexEntries) GetEntries() []*IndexEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type IndexBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IndexEntries  *IndexEntries `protobuf:"bytes,1,opt,name=index_entries,json=indexEntries,proto3" json:"index_entries,omitempty"`
	RestartPoints []uint32      `protobuf:"varint,2,rep,packed,name=restart_points,json=restartPoints,proto3" json:"restart_points,omitempty"`
}

func (x *IndexBlock) Reset() {
	*x = IndexBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sst_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexBlock) ProtoMessage() {}

func (x *IndexBlock) ProtoReflect() protoreflect.Message {
	mi := &file_sst_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexBlock.ProtoReflect.Descriptor instead.
func (*IndexBlock) Descriptor() ([]byte, []int) {
	return file_sst_proto_rawDescGZIP(), []int{6}
}

func (x *IndexBlock) GetIndexEntries() *IndexEntries {
	if x != nil {
		return x.IndexEntries
	}
	return nil
}

func (x *IndexBlock) GetRestartPoints() []uint32 {
	if x != nil {
		return x.RestartPoints
	}
	return nil
}

type Footer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockHandle *BlockHandle `protobuf:"bytes,1,opt,name=block_handle,json=blockHandle,proto3" json:"block_handle,omitempty"`
	Version     uint32       `protobuf:"fixed32,2,opt,name=version,proto3" json:"version,omitempty"`
	Magic       uint64       `protobuf:"fixed64,3,opt,name=magic,proto3" json:"magic,omitempty"`
}

func (x *Footer) Reset() {
	*x = Footer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sst_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Footer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Footer) ProtoMessage() {}

func (x *Footer) ProtoReflect() protoreflect.Message {
	mi := &file_sst_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Footer.ProtoReflect.Descriptor instead.
func (*Footer) Descriptor() ([]byte, []int) {
	return file_sst_proto_rawDescGZIP(), []int{7}
}

func (x *Footer) GetBlockHandle() *BlockHandle {
	if x != nil {
		return x.BlockHandle
	}
	return nil
}

func (x *Footer) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Footer) GetMagic() uint64 {
	if x != nil {
		return x.Magic
	}
	return 0
}

var File_sst_proto protoreflect.FileDescriptor

var file_sst_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x73, 0x73, 0x74,
	0x1a, 0x18, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x62, 0x2f, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb8, 0x01, 0x0a, 0x0a, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x6e, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x75, 0x6e, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x64, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0c, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x4c, 0x65, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x64, 0x62, 0x2e, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x22, 0x39, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x07, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x22, 0xa6, 0x01, 0x0a, 0x0a, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x75,
	0x6e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0b, 0x75, 0x6e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x12, 0x24,
	0x0a, 0x0e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x6c, 0x65, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x4b, 0x65,
	0x79, 0x4c, 0x65, 0x6e, 0x12, 0x33, 0x0a, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x73, 0x74,
	0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x0b, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x22, 0x3d, 0x0a, 0x10, 0x44, 0x61, 0x74,
	0x61, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x29, 0x0a,
	0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x73, 0x73, 0x74, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x77, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x43, 0x0a, 0x12, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x73, 0x73, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x10, 0x64, 0x61, 0x74, 0x61, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0d, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x22, 0x39, 0x0a, 0x0c, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x12, 0x29, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x6b, 0x0a, 0x0a,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x36, 0x0a, 0x0d, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x73, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x45, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x52, 0x0c, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x45, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x6d, 0x0a, 0x06, 0x46, 0x6f, 0x6f,
	0x74, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x73, 0x74, 0x2e,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x0b, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x06, 0x52, 0x05, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x61, 0x72, 0x74, 0x69, 0x6e, 0x53, 0x69, 0x6d,
	0x61, 0x6e, 0x67, 0x6f, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2d, 0x64, 0x62, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x62, 0x2f, 0x73, 0x73, 0x74, 0x3b, 0x73,
	0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sst_proto_rawDescOnce sync.Once
	file_sst_proto_rawDescData = file_sst_proto_rawDesc
)

func file_sst_proto_rawDescGZIP() []byte {
	file_sst_proto_rawDescOnce.Do(func() {
		file_sst_proto_rawDescData = protoimpl.X.CompressGZIP(file_sst_proto_rawDescData)
	})
	return file_sst_proto_rawDescData
}

var file_sst_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sst_proto_goTypes = []interface{}{
	(*BlockEntry)(nil),       // 0: sst.BlockEntry
	(*BlockHandle)(nil),      // 1: sst.BlockHandle
	(*IndexEntry)(nil),       // 2: sst.IndexEntry
	(*DataBlockEntries)(nil), // 3: sst.DataBlockEntries
	(*DataBlock)(nil),        // 4: sst.DataBlock
	(*IndexEntries)(nil),     // 5: sst.IndexEntries
	(*IndexBlock)(nil),       // 6: sst.IndexBlock
	(*Footer)(nil),           // 7: sst.Footer
	(db.RecordType)(0),       // 8: db.RecordType
}
var file_sst_proto_depIdxs = []int32{
	8, // 0: sst.BlockEntry.record_type:type_name -> db.RecordType
	1, // 1: sst.IndexEntry.block_handle:type_name -> sst.BlockHandle
	0, // 2: sst.DataBlockEntries.entries:type_name -> sst.BlockEntry
	3, // 3: sst.DataBlock.data_block_entries:type_name -> sst.DataBlockEntries
	2, // 4: sst.IndexEntries.entries:type_name -> sst.IndexEntry
	5, // 5: sst.IndexBlock.index_entries:type_name -> sst.IndexEntries
	1, // 6: sst.Footer.block_handle:type_name -> sst.BlockHandle
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_sst_proto_init() }
func file_sst_proto_init() {
	if File_sst_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sst_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sst_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockHandle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sst_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sst_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataBlockEntries); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sst_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sst_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexEntries); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sst_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sst_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Footer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sst_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sst_proto_goTypes,
		DependencyIndexes: file_sst_proto_depIdxs,
		MessageInfos:      file_sst_proto_msgTypes,
	}.Build()
	File_sst_proto = out.File
	file_sst_proto_rawDesc = nil
	file_sst_proto_goTypes = nil
	file_sst_proto_depIdxs = nil
}
